### ISSUE TITLE
How to set the node properties?

### ISSUE THREAD

**Issue by GRomRepo** [rabbitmq/rabbitmq-amqp1.0-client#42]
Hello. I use the client to work with activeMQ.
But I can't set node properties for delete queue without any link of consumer.
As I understand, I should set it in "lifetime-policy" in field "dynamic-node-properties" of source when I'm attaching a receiver.
But I can't understand how to do it.
Help me please. How to set it correctly?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by lukebakken** [comment]
Please ask questions on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list in the future.

@kjnilsson pointed me to [this code](https://github.com/rabbitmq/rabbitmq-amqp1.0-client/blob/master/src/amqp10_msg.erl#L26-L32) and suggested that you may need to set `message_annotations`.

**Comment by GRomRepo** [comment]
thanks
